name: 'PMD - Salesforce APEX code analyzer action'
author: Leo Jokinen
description: 'Check Salesforce APEX code using PMD'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'award'  
  color: 'red'
